config/routes.rb
Rails.application.routes.draw do
  resources :past_cats
  resources :cats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_one :past_cat
end

app/models/past_cat.rb
class PastCat < ApplicationRecord
  belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.left_joins(:past_cat).where("past_cats.id IS NULL")
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:kind, :sex, :age, :size, :color, :place, :limit, :detail, :image)
    end
end

app/controllers/past_cats_controller.rb
class PastCatsController < ApplicationController
  before_action :set_past_cat, only: [:show, :edit, :update, :destroy]

  # GET /past_cats
  # GET /past_cats.json
  def index
    @past_cats = PastCat.joins(:cat)
  end

  # GET /past_cats/1
  # GET /past_cats/1.json
  def show
  end

  # GET /past_cats/new
  def new
    @past_cat = PastCat.new
  end

  # GET /past_cats/1/edit
  def edit
  end

  # POST /past_cats
  # POST /past_cats.json
  def create
    @past_cat = PastCat.new(past_cat_params)

    respond_to do |format|
      if @past_cat.save
        format.html { redirect_to @past_cat, notice: 'Past cat was successfully created.' }
        format.json { render :show, status: :created, location: @past_cat }
      else
        format.html { render :new }
        format.json { render json: @past_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /past_cats/1
  # PATCH/PUT /past_cats/1.json
  def update
    respond_to do |format|
      if @past_cat.update(past_cat_params)
        format.html { redirect_to @past_cat, notice: 'Past cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @past_cat }
      else
        format.html { render :edit }
        format.json { render json: @past_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /past_cats/1
  # DELETE /past_cats/1.json
  def destroy
    @past_cat.destroy
    respond_to do |format|
      format.html { redirect_to past_cats_url, notice: 'Past cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_past_cat
      @past_cat = PastCat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def past_cat_params
      params.require(:past_cat).permit(:cat_id, :whereabouts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/past_cats_helper.rb
module PastCatsHelper
end

app/views/cats/_form.html.erb
<%= form_with(model: cat, local: true) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kind %>
    <%= form.text_field :kind, id: :cat_kind %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :cat_sex %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age, id: :cat_age %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :cat_size %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :cat_color %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :cat_place %>
  </div>

  <div class="field">
    <%= form.label :limit %>
    <%= form.date_select :limit, id: :cat_limit %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail, id: :cat_detail %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :cat_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cats</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Sex</th>
      <th>Age</th>
      <th>Size</th>
      <th>Color</th>
      <th>Place</th>
      <th>Limit</th>
      <th>Detail</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.kind %></td>
        <td><%= cat.sex %></td>
        <td><%= cat.age %></td>
        <td><%= cat.size %></td>
        <td><%= cat.color %></td>
        <td><%= cat.place %></td>
        <td><%= cat.limit %></td>
        <td><%= cat.detail %></td>
        <td><%= cat.image %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @cat.kind %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @cat.sex %>
</p>

<p>
  <strong>Age:</strong>
  <%= @cat.age %>
</p>

<p>
  <strong>Size:</strong>
  <%= @cat.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cat.color %>
</p>

<p>
  <strong>Place:</strong>
  <%= @cat.place %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @cat.limit %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @cat.detail %>
</p>

<p>
  <strong>Image:</strong>
  <%= @cat.image %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/past_cats/_form.html.erb
<%= form_with(model: past_cat, local: true) do |form| %>
  <% if past_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(past_cat.errors.count, "error") %> prohibited this past_cat from being saved:</h2>

      <ul>
      <% past_cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cat_id %>
    <%= form.text_field :cat_id, id: :past_cat_cat_id %>
  </div>

  <div class="field">
    <%= form.label :whereabouts %>
    <%= form.text_field :whereabouts, id: :past_cat_whereabouts %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/past_cats/edit.html.erb
<h1>Editing Past Cat</h1>

<%= render 'form', past_cat: @past_cat %>

<%= link_to 'Show', @past_cat %> |
<%= link_to 'Back', past_cats_path %>

app/views/past_cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Past Cats</h1>

<table>
  <thead>
    <tr>
      <th>Cat</th>
      <th>Whereabouts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @past_cats.each do |past_cat| %>
      <tr>
        <td><%= past_cat.cat %></td>
        <td><%= past_cat.whereabouts %></td>
        <td><%= link_to 'Show', past_cat %></td>
        <td><%= link_to 'Edit', edit_past_cat_path(past_cat) %></td>
        <td><%= link_to 'Destroy', past_cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Past Cat', new_past_cat_path %>

app/views/past_cats/new.html.erb
<h1>New Past Cat</h1>

<%= render 'form', past_cat: @past_cat %>

<%= link_to 'Back', past_cats_path %>

app/views/past_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cat:</strong>
  <%= @past_cat.cat %>
</p>

<p>
  <strong>Whereabouts:</strong>
  <%= @past_cat.whereabouts %>
</p>

<%= link_to 'Edit', edit_past_cat_path(@past_cat) %> |
<%= link_to 'Back', past_cats_path %>